### ISSUE TITLE
Transitioning from and to the same state

### ISSUE THREAD

**Issue by Czyzuniu** [luisoliveiras/scriptable-states#11]
Hi, 

I am trying to run an action inside a state on state enter (Triggering animation). This works, but then my state has a transition to itself, when that happens for some reason the state instead of running the start action once it seems to run it every frame.

I am trying to implement a very basic AI

CHASE -> IF within CLOSE  range -> CLOSE ATTACK ELSE CHASE

CHASE -> IF within LONG range -> LONG ATTACK ELSE CHASE

ATTACK -> IF WITHIN CLOSE RANGE -> KEEP ON DOING CLOSE ATTACK ELSE CHASE

What issue I am having, is that when a state ATTACK transitions to itself because the player is still within range, it seems to run the action every frame. The action is setting a trigger for an attack animation to play, which then sets the trigger multiple times, causing attack animation to be played, after the state is already over.

I guess I could probably have an exit state with an action to clear a trigger, but I think that seems wrong. Is this the intended behavior?

Another problem that I am having is that the LONG ATTACK state never triggers when a CLOSE ATTACK is added to the list of possible states, it seems to happen because I use the same Condition script but different scriptable objects, I was trying to use the same scriptable script, for range, and create 2 different conditions with different values 

e.g 
close range condition -> min distance 0 max distance <= 5 
long range condition -> min distance 20 max distance <= 100 

`  [CreateAssetMenu(menuName = "Scriptable State Machine/Conditions/Range", fileName = "new Within Range")]
  public class WithinRange : ScriptableCondition {
    [SerializeField]
    private float minDistance;
    
    [SerializeField]
    private float maxDistance;
    
    
    public override bool Verify(StateComponent statesComponent) {
      BaseBehaviour behaviour = statesComponent.GetComponent<BaseBehaviour>();
      float distanceToTarget = behaviour.DistanceBetweenTarget();
      bool inRange = distanceToTarget > minDistance && distanceToTarget <= maxDistance;
      bool isFacingTarget = behaviour.FacingTarget();
     
      return inRange && isFacingTarget;
    }
    
  }`

Thank you for your help

**Comment by luisoliveiras** [comment]
Hello!
So, if you make a transition to the same state, then you will go through all of its events (onStateExit and onStateEnter). 
If you want to stay in the same state, you use empty state as your TrueState, in that transition, so instead of transitioning to the same state again, it will keep you in that state.

**Comment by Czyzuniu** [comment]
I see that makes sense. I made the change and it works as intended.

What about the 2nd issue, where I use the same scriptable object script, but different values, as mentioned above, I have a Within Range script, and 2 instances of that script, once called CLOSE and second RANGE, both have different min and max range set.

When I do that it seems like the state will never transition to the RANGE state

picture of my state - https://ibb.co/1qcCkmS
picture of my scriptable objects - https://ibb.co/phyGmKS

WithinRange script is in the comment above.

For reference, SMASH is the close-range attack and RANGED_ATTACK is the distance attack

Thank you very much for this package, and thank you for all of the help.

**Comment by luisoliveiras** [comment]
The transitions are evaluated in the order you put them into the list. Try moving the CHASE > RANGED to the second slot of the list (or even the first, depending on the priority of your ranged attacks), and see if that works for you.
The idea of the scriptable is to solve problemas like that, so won't have any problems with runing multiple instances of it.

**Comment by Czyzuniu** [comment]
Unfortunately, moving the RANGED attack to the top of the list, causes the AI to never do the CLOSE attack, as soon as I get within the CLOSE attack range, it goes back to CHASE, close attack will only transition if I move the states around within the inspector during run time, then it will do the CLOSE attack but never do RANGE attack

**Comment by luisoliveiras** [comment]
Seeing the image again, I think I get the problem. You are transitioning back to the CHASE state. Try setting both false states for the CHASE transitions to Empty State. That way, it will not transition back to the chase state, leaving the oportunity for the other transition to be evaluated. Remember that if you use the Empty State as a target state, it will not make a transition and will remain on the current state. The way that I made it, it will transition to the first valid state. If both true and false states are valid transitions (not empty state) then it will have a transition and will have the transition and ignore the others.

**Comment by luisoliveiras** [comment]
Hi there, did this solution solve your problem?
