### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by garlen-javier** [luisoliveiras/scriptable-states#7]
I got this error when trying to build my project with this package.
Unity Version: 2020.3.5f1

```
Library\PackageCache\com.loophouse.scriptable-states@6e87c29b57\Runtime\ScriptableState.cs(3,7): error CS0246: The type or namespace name 'UnityEditorInternal' could not be found (are you missing a using directive or an assembly reference?)
```

Screenshot:
![buildErrorUnity](https://user-images.githubusercontent.com/71249192/120609760-195aaf00-c485-11eb-84b0-9635abb47ef6.PNG)

**Comment by luisoliveiras** [comment]
I'll mak a quick fix here for you. It seems UnityEditorInternal no longer exists on 2020.3. I'll remove it and launch a hotfix.

**Comment by luisoliveiras** [comment]
Release v0.3.1 is available, just let me know if it works

**Comment by garlen-javier** [comment]
Yes removing it fix it, thanks
