### ISSUE TITLE
Minor Request:

### ISSUE THREAD

**Issue by garlen-javier** [luisoliveiras/scriptable-states#9]
Please add a way to get the previous state. Can do it manually but maybe it is good if it will be built-in already in the package. Also a way to detect if the state is change or like a callback, onChangState

**Comment by luisoliveiras** [comment]
Thanks for the suggestions, right now I'm working on a new version for this package and it will come with a few changes on it's structure.  Can you provide a use case for those requests so I can understand it better? I could even put it in this next release.

**Comment by garlen-javier** [comment]
PreviousState Sample UseCase:
- Since states can be called from any other states, having to know the previous states can verify some certain conditions to use on next state.
Pseudo Example:
//if true proceed to level2state
CountDownState Condition
  If previousState == level1State
     return true
  
CallBack OnChangeState(prevSate,currState) Sample Use Case.
- Same reason as first but can have different purpose or optional usage.
- Could be easily called and use on monobehavior scripts.
Pseudo Example:
Game.cs
OnChangeState(prevState,currState)
{
 myPlayer.updateGameState(currState);
}

**Comment by luisoliveiras** [comment]
Just released a new version( and it comes with some changes on how the states and state component works(I recommend you putting it on another project first to see how it works now). I also added a callback to the state component so you can subscribe to the OnStateChanged and get the previous state and current state as soon as it changes.

**Comment by garlen-javier** [comment]
Trying out the new version, did a test on the sample on ChangeSpriteColorAction script. I still think having a getter for previousState would be nice as state actions and condition are called in `Update` and `LateUpdate` so I'm not sure how I could subscribe/unsubscribe to event efficiently or I am missing something?. Or for entry state it can be called multiple times also when the state is in use again. In monobehavior it is ok as I can subscribe/unsubscribe inside OnEnable and OnDisable.

```c#
public class ChangeSpriteColorAction : ScriptableAction
{
	public Color newColor = Color.white;

    public override void Act(StateComponent statesComponent)
	{
		if (statesComponent.OnStateChanged == null) //Can be *not null* as other scripts can subscribe to it
		{
			Debug.Log("ChangeSpriteColorAction"); // got called twice
			statesComponent.OnStateChanged += OnUpdateState;
		}

		statesComponent.GetComponent<SpriteRenderer>().color = newColor;
	}

	void OnUpdateState(ScriptableState prev, ScriptableState curr)
	{
		Debug.Log(prev.name);
		Debug.Log(curr.name);
	}
}
```

**Comment by luisoliveiras** [comment]
Are you trying to make the action run only once? If so, just drop it in the entry/exit actions, depending on when you need them to run. Entry/Exit actions are called only once when there is a state transition. Note that when the transition returns an empty state, the current state remains the same and there is no transition. If the transition returns a state other than the empty state, then you get a transition, even if it is a transition for the same state, and then you get all the steps from the transition run (exit actions from previous state and then entry actions from the new state).

**Comment by garlen-javier** [comment]
I understand that but in use case like a countdown timer like before proceeding to another state you need to know the previous state in order to reuse effectively the countdown state.

Example Scenario:
State: CountDownState 
Action: CountDownRunning - "reusable counter: 3,2,1 and go"
Condition: CountDown1Finish

States to transitions: Level1, Level2, Level3 - this states can have its own timer too.

Let say In between Level 1 and Level 2 I put the CountdownState, then how would I determine in ` CountDownFinish`  condition that the previous state was Level 1 and not other Level? 
From State Machine it would be like this:

**Element 0:**
Origin State: Level1
Condition: Level1TimerFinish
True:  CountdownState
False: Empty 

**Element 1:**
Origin State: CountdownState
Condition : Countdown1Finish - "It would be set true if the code determines that the previous state is Level 1 not 3  or 4"
True:  Level2 - "Then like Element 0, it will change to CountdownState again"
False: Empty 

So my problem is how would I **recycle CountdownState** that also got different condition to use before changing to the next level state. Ideally Countdown1Finish code would look like this.

```c#
public class Countdown1Finish  : ScriptableCondition
{
    public ScriptableState  level1State;
    public override bool Verify(StateComponent statesComponent)
    {
        return statesComponent.previousState == level1State
    }
}
```

**Comment by luisoliveiras** [comment]
Ok, now I get what you're trying. I'll make some tests here with this idea and as soon as I get to something useful I'll let you know. While I work on it, you could use something like this to solve your problem for now:

``` csharp
public class LastStateRecorder : MonoBehaviour
{
    [SerializeField] private StateComponent _stateComponent;

    public ScriptableState PreviousState { get; private set; }

    private void OnEnable()
    {
        _stateComponent.OnStateChanged += OnTransitionFinished;
    }

    private void OnDisable()
    {
        _stateComponent.OnStateChanged -= OnTransitionFinished;
    }

    private void OnTransitionFinished(ScriptableState previousState, ScriptableState currentState)
    {
        PreviousState = previousState;
    }
}
```
And your condition would look like this:

``` csharp
public class CountdownFinish  : ScriptableCondition
{
    public ScriptableState  levelState;
    public override bool Verify(StateComponent statesComponent)
    {
        var lastState = statesComponent.GetComponent<LastStateRecorder>().PreviousState;
        return lastState == levelState;
    }
}
```
This is mostly how I access info from classes other than the StateComponent right now. I could expand that to give it a bit more functionality, like record the past transitions history and more, but I tried to keep it simple for the problem you brought. Hope it helps!
